const apiHost = "https://picsum.photos/v2";
const apiEndpoint = "/list?page=%s&limit=%s";
const startPage = 0;
const defaultLimit = 10;
const nullPlaceholder = "n/a";
const nullUri = "http://mock.io";
const placeholderUri = "asserts/images/img_placeholder.png";
const errorUri = "asserts/images/img_error.png";
const lineCount = 2;
